### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by shmokmt** [ssh0/dot#15]
### Environment
- zsh (zplug)

### Image

![image](https://user-images.githubusercontent.com/32533860/53695167-6f020600-3dfb-11e9-9c90-1b0433d8f811.png)

Nice to meet you. I'm a Japanese developer too. I found a bug.
I also try to install via zplug NOT manually. But, it does not work correct too. 😢

**Comment by ssh0** [comment]
Thank you for your report.

It occurs because of your alias of `pwd` or `cd`.
Please tell me your aliases for `pwd` or `cd`.

**Comment by ssh0** [comment]
@sh-tech
