### ISSUE TITLE
宛先にディレクトリが存在するとdot setの(b):replace and make backupがうまくいかない

### ISSUE THREAD

**Issue by crhg** [ssh0/dot#9]
既に古い`~/.vim`ディレクトリがある状態で`dot set .vim`を行い、`(b):replace and make backup`を選択したら、`~/.vim`がバックアップされて置き換わるのではなく`~/.vim/.vim`というsymbolic linkが作成されてしまいました。

ln -sbは宛先がディレクトリだとこの場合に期待する動作にはならないので、mvしてlnするのがいいのではないかと思います。

**Comment by ssh0** [comment]
ありがとうございます。修正しました。
